### ISSUE TITLE
"sendor not an eoa" on running aida-vm with protobuf substate

### ISSUE THREAD

**Issue by rpl-ffl** [Fantom-foundation/Aida#1156]
### Observation:
On running `aida-vm` with protobuf substate, an error `sender not an eoa` is observed. This error is seemingly coming from Tosca, even though the `aida-vm` call should not reach any Tosca implementation.

https://github.com/Fantom-foundation/Tosca/blob/96d3fed80862f34d21fb1c0e5572546486718ad3/go/processor/opera/processor.go#L99

https://github.com/Fantom-foundation/Tosca/blob/96d3fed80862f34d21fb1c0e5572546486718ad3/go/processor/opera/processor.go#L347C2-L350C2

```
// aida-vm call
$ build/aida-vm --validate --log debug  --workers 1 --chainid 1 --evm-impl aida --vm-impl geth --aida-db <PATH> --db-logging temp.log 19500000 19600000

2024/09/05 11:41:28 WARNING: given aida-db does not contain metadata; please generate them using util-db metadata generate
2024/09/05 11:41:28 WARNING: Temporary directory  is not found. Use the system default /tmp.
2024/09/05 11:41:28 NOTICE: Run config:
2024/09/05 11:41:28 INFO: Block range: 19500000 to 19600000
2024/09/05 11:41:28 INFO: Chain id: 1 (record & run-vm only)
2024/09/05 11:41:28 INFO: SyncPeriod length: 300
2024/09/05 11:41:28 NOTICE: Used EVM implementation: geth
2024/09/05 11:41:28 NOTICE: Used VM implementation: geth
2024/09/05 11:41:28 INFO: Aida DB directory: /home/rapolt/dev/data/19.5-20M
2024/09/05 11:41:28 INFO: validate tx state: true
2024/09/05 11:41:28 WARNING: Db logging enabled, reducing Tx throughput
2024/09/05 11:41:28 WARNING: Transaction verification is enabled, this may slow down the block processing.
2024/09/05 11:41:28 DEBUG: Starting 1 workers run on Transaction granularity...

// HERE:
block: 19500001 transaction: 0
sender not an eoa: address 0xa07049FF3B687671b7dd62104Cb9Fd3b5f1062C2, codehash: 0x10ca3eff73ebec87d2394fc58560afeab86dac7a21f5e402ea0a55e5c8a6758f
```

### Note

The bug has already been fixed in this [commit](https://github.com/Fantom-foundation/Substate/commit/7b99eb43bb4f2d4017307340b6f6866c6bb65a27).
The cause is that `codehash` was erroneously provided instead of `code`.
However, it is not expected for a call that only involves geth to reach Tosca.

### Steps to Reproduce
1. Clone and build Aida 
```
git clone git@github.com:Fantom-foundation/Aida.git
cd Aida
git checkout rapol/reproduce-bug/protobuf-sender-not-eoa
git submodule update --init --recursive
make -j aida-vm
```

2. Prepare aida-db
```
wget https://elc.yonsei.ac.kr/record-replay/rr0.5-substate-db/rr0.5.substate.ethereum.19.5-20M.tar.zst
tar --zstd -xvf rr0.5.substate.ethereum.19.5-20M.tar.zst
```

3. Make the aida-vm call
```
# Where PATH is the path to the extracted aida-db in step 2
$ build/aida-vm --validate --log debug  --workers 1 --chainid 1 --evm-impl aida --vm-impl geth --aida-db <PATH> --db-logging temp.log 19500000 19600000
```

**Comment by HerbertJordan** [comment]
It looks like the issue is caused by this check in Sonic: [here](https://github.com/Fantom-foundation/Sonic/blob/6e32fbceb88fad8ad1f9643082105281a50d1b39/evmcore/state_transition.go#L227-L231)

This appears to check that only accounts without associated code are allowed to send in transactions.

In ethereum, it looks like this is an optional features ([here](https://github.com/ethereum/go-ethereum/blob/af794ef682bc2c481ccf9ad01d3492910c50ce61/core/state_transition.go#L301-L308)), which is now guarded by the `!msg.SkipFromEOACheck`. But this is only two weeks old ([here](https://github.com/ethereum/go-ethereum/commit/8f4fac7b86227e3ceca095e60d58f126d692f379)). Before it was also guarded by `!msg.SkipAccountChecks` which I think is the new of the `msg.IsFake()` used in Sonic.

If you update to the development branch of Sonic, to match geth 1.14.8, you will see that also in Sonic [`!msg.SkipAccountChecks`](https://github.com/Fantom-foundation/Sonic/blob/8e5ede0624be3df10324f235e9058b6eef63d2ee/evmcore/state_transition.go#L207) is checked.

I would suggest the following:
- update the sonic dependency to the latest `Sonic/development` branch
- check in the decoding of the ethereum substate protobuffers whether you can find something that would indicate whether `SkipAccountChecks` should be set; usually those would be internal transactions;

**Comment by HerbertJordan** [comment]
>The bug has already been fixed in this [commit](https://github.com/Fantom-foundation/Substate/commit/7b99eb43bb4f2d4017307340b6f6866c6bb65a27).
> The cause is that codehash was erroneously provided instead of code.

Alright, ignore the message above.

About this:
> However, it is not expected for a call that only involves geth to reach Tosca.

The issue is happening inside the geth transaction processor, which is active even when running a Tosca interpreter. It is plausible  that this error would be produced.

If you want to side-step even the geth transaction processor and use Tosca's processor instead, you need to pass the `--evm-impl floria` flag. However, `floria` is under development and not expected to be feature complete.
